"""add analysis source to resume analyses

Revision ID: 089b484eaf13
Revises: a0623be15df3
Create Date: 2026-06-08 16:22:44.974020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089b484eaf13'
down_revision: Union[str, Sequence[str], None] = 'a0623be15df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "resume_analyses",
        sa.Column(
            "analysis_source",
            sa.String(length=50),
            nullable=False,
            server_default="mock",
        ),
    )


def downgrade() -> None:
    op.drop_column("resume_analyses", "analysis_source")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_analyses', 'analysis_source')
    # ### end Alembic commands ###
